config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees 
  resources :employees do
    resources :queries do 
      resources :comments
    end
  end

     post '/employees/:id' => 'employees#employee_session' , as: :checkin_time

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
	belongs_to :company 
	belongs_to :branch
	belongs_to :work_shift
	belongs_to :job_title
	belongs_to :job_category
	has_many :queries , :class_name => 'Query', :foreign_key => 'creater_id'
	has_many :comments, :class_name => 'Comment', :foreign_key => 'commenter_id'
	has_many :employee_sessions
	has_and_belongs_to_many :skills
	has_and_belongs_to_many :educations 

  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :educations

  def current_session
  	session = employee_sessions.last
  	if(session.blank? || (session.check_in? && session.check_out?))
  		session = employee_sessions.create!
  	else	
  		session
  	end
  end	
end

app/controllers/employee/confirmations_controller.rb
class Employee::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employee/omniauth_callbacks_controller.rb
class Employee::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employee/passwords_controller.rb
class Employee::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employee/registrations_controller.rb
class Employee::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   employee_path(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employee/sessions_controller.rb
class Employee::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employee/unlocks_controller.rb
class Employee::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	
	def index
		@employee = Employee.all
		@branch = Branch.find(current_employee.branch_id)
		@company =Company.find((current_employee.company_id))

	end

	def show
		@employee = Employee.find(params[:id])	
	end

	def employee_session
		byebug
		@employee = Employee.find(params[:id])
		@employee.create_employee_session.check_in

	end

end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
<div class="panel-heading">Employee List</div>
<div class="panel-body">
  <table class="table"">
    <thead>
      <tr>
        <th >Username</th>
        <th >Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
    <% @branch.employees.each do |branch| %>
    <tr>
      <td ><%= branch.username %></td>
		    <td ><%= branch.email %></td>
    <% end %>
  </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<%- model_class = Employee -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/employees/show.html.erb
<div class="panel panel panel-info"> 
  <div class="panel-heading">
    <h2 class="panel-title">Employee</h2>
  </div>
</div>  
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Username: <%= @employee.username %></h3>
  </div> 
  <div class="panel-heading">
    <h3 class="panel-title">Email: <%= @employee.email %></h3>
  </div>
  <div class="panel-heading">
    <h3 class="panel-title">Company Name: <%= @employee.company.title %></h3>
  </div>
  <div class="panel-heading">
    <h3 class="panel-title">Branch Name: <%= @employee.branch.title %></h3>
  </div>  
  <div class="panel-heading">
    <h3 class="panel-title">Job Title: <%= @employee.job_title.title  %></h3>
  </div>
  <div class="panel-heading">
    <h3 class="panel-title">Job Category: <%= @employee.job_category.title  %></h3>
  </div>
  <div class="panel-heading">
    <h3 class="panel-title">Work Shift: <%= @employee.work_shift.title %></h3>
  </div>
  <div class="panel-heading">
    <h3 class="panel-title">Skillls: <%@employee.skills.each do |skill| %>
      <%= skill.title%>,
     <% end -%></h3>
  </div> 
  <div class="panel-heading">
    <h3 class="panel-title">Education:<%@employee.educations.each do |education| %>
      <%= education.title%>, 
    <% end -%></h3>
  </div>
  </div>
  <div class="button">
  <%= link_to 'Submit Queries',employee_queries_path(@employee),class: "btn btn-primary"%>
</div>