config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees 
  resources :employees do
    resources :queries do 
      resources :comments
    end
  end

     post '/employees/:id' => 'employees#employee_session' , as: :checkin_time

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/branch.rb
class Branch < ActiveRecord::Base
	belongs_to :company	
	has_many :employees	

  geocoded_by :full_address 
  after_validation :geocode 

  def full_address

  	[address_line_1, city, state,zipcode, country].compact.join(', ')
  end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :commenter, class_name: 'Employee' ,:foreign_key => 'commenter_id'
end

app/models/company.rb
class Company < ActiveRecord::Base
	mount_uploader :logo, ImageUploader
	mount_uploader :banner, ImageUploader
	
	has_many :branches
	has_many :employees
	
end

app/models/education.rb
class Education < ActiveRecord::Base

	has_and_belongs_to_many :employees

	validates :title , :presence=> true 
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
	belongs_to :company 
	belongs_to :branch
	belongs_to :work_shift
	belongs_to :job_title
	belongs_to :job_category
	has_many :queries , :class_name => 'Query', :foreign_key => 'creater_id'
	has_many :comments, :class_name => 'Comment', :foreign_key => 'commenter_id'
	has_many :employee_sessions
	has_and_belongs_to_many :skills
	has_and_belongs_to_many :educations 

  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :educations

  def current_session
  	session = employee_sessions.last
  	if(session.blank? || (session.check_in? && session.check_out?))
  		session = employee_sessions.create!
  	else	
  		session
  	end
  end	
end

app/models/employee_session.rb
class EmployeeSession < ActiveRecord::Base
	belongs_to :employee


	def check_in
		checkin_time = Time.now
		save
	end

	def check_out
		checkout_time = Time.now
		duration = checkout_time - checkin_time 
		save
	end

	def check_in?
		!checkin_time.blank?
	end

	def check_out?
		!checkout_time.blank?
	end

end

app/models/employment_status.rb
class EmploymentStatus < ActiveRecord::Base
	validates :title , :presence=> true 
end

app/models/job_category.rb
class JobCategory < ActiveRecord::Base

has_many :employees
	
	validates :title ,:presence => true 
end

app/models/job_title.rb
class JobTitle < ActiveRecord::Base

	has_many :employees


	validates :title , :presence=> true 
	validates :description ,:presence => {:minimum =>50 ,:message=>"Please Provide Your Description in Minimum 50 Words ."} 
	validates :specification , :presence=> true 
	validates :note , :presence=> {:maixmum => 100 , :message=> "Please Provide Your Note in Maximum 100 Words ."}
end

app/models/language.rb
class Language < ActiveRecord::Base

	validates :title , :presence=> true 
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/query.rb
class Query < ActiveRecord::Base
	has_many :comments
	belongs_to :creater , class_name: 'Employee', :foreign_key => 'creater_id'
end

app/models/skill.rb
class Skill < ActiveRecord::Base

	has_and_belongs_to_many :employees

	validates :title , :presence => {:message=> "Plese Enter The Title "} 
	validates :description , :presence => true ,
	 									:length=> {:minimum => 10, :message=>"minimum 50 Words"}
end

app/models/work_shift.rb
class WorkShift < ActiveRecord::Base

	has_many :employees

	validates :start_time ,:end_time, :presence => {:message=>"Field Must Be present ?"}
	validates	:title , :presence => true
  before_save :time_diff
    
		def time_diff
	  	diff_array = [self.start_time,self.end_time].collect{|a| a.split(":").collect{|s| s.to_i}}
	  	diff_array[1][1]+=60
	  	diff_array[1][0]-=1
	  	diff_hor = diff_array[1][0] - diff_array[0][0]
	  	diff_min = diff_array[1][1] - diff_array[0][1]

	  	diff_hor += (diff_min / 60)
	  	diff_min = (diff_min % 60)
	  	self.duration  = "#{diff_hor.to_s.rjust(2,'0')}:#{diff_min.to_s.rjust(2,'0')}"
 		end	

 		def self.time_calc
  	  (0..23).to_a.collect{|a| a.to_s.rjust(2,"0")}.collect{ |a| ["00","15","30","45"].collect{ |b| "#{a}:#{b}"  }  }.flatten
    end 
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_employee!

	
  def after_sign_in_path_for(resource)
  	if resource.class.to_s.eql? "Employee"   
    	employee_path(resource)
    else	
    	admin_dashboard_url
    end	
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :query ,	only: [:index, :new, :create, :show]
  
	def index

	end

	def new
		@comment= Comment.new 
	
	end

	def create
		@comment = @query.comments.new(comment_params)
		@comment.commenter = current_employee	
		if @comment.save 
		  redirect_to employee_query_path(@comment.commenter, @query)
		else
			render "new"
		end
		def show
			
		end
	end

	
	private
		def query
			@query = Query.find(params[:query_id])
		end

		def comment_params
      params.require(:comment).permit(:description)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

	
	def index
		@employee = Employee.all
		@branch = Branch.find(current_employee.branch_id)
		@company =Company.find((current_employee.company_id))

	end

	def show
		@employee = Employee.find(params[:id])	
	end

	def employee_session
		byebug
		@employee = Employee.find(params[:id])
		@employee.create_employee_session.check_in

	end

end

app/controllers/queries_controller.rb
class QueriesController < InheritedResources::Base
 before_action :employee , only: [:index ,:new]
 before_action :query , only: [:show ]

	def index
		@queries = Query.all
	end

	def create 
		@query = Query.new(query_params)
		@query.creater = current_employee
		byebug
		if @query.save
			redirect_to employee_queries_path
		else
			render "new"
		end
	end	
 
	def show
  		
	end



  private

  def employee
  	@employee =Employee.find(params[:employee_id])
  end

  def query
  	@query = Query.find(params[:id])
  end
  
  def query_params
    params.require(:query).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def custom_bootstrap_flash
	  flash_messages = []
	  flash.each do |type, message|
	    type = 'success' if type == 'notice'
	    type = 'error'   if type == 'alert'
	    text = "<script>toastr.#{type}('#{message}');</script>"
	    flash_messages << text.html_safe if message
	  end
	  flash_messages.join("\n").html_safe
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_form.html.erb
<%= form_for ([@employee, @employee.queries.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/queries/edit.html.erb
<h1>Editing Query</h1>

<%= render 'form' %>

<%= link_to 'Show', @query %> |
<%= link_to 'Back', queries_path %>

app/views/queries/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-warning">
<div class="panel-heading">Listing Queries</div>
  <div class="panel-body">
    <table class="table table-condensed ">
      <thead>     
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
          <% @queries.each do |query| %>
            <tr>
              <td> <%= query.creater.username %></td>
              <td><%= query.title %></td>
              <td><%= query.description %></td>
              <td><%= button_to 'Show', employee_query_path(query.creater.id,query.id),method: 'get' %>
              </td>
            </tr> 
          <% end %>
      </tbody>
    </table> 
  </div>  
</div>
<div class="panel panel-warning">
  <div class="panel-heading"> <h4>Submit Queries</h3> </div>
      <%= render partial: 'form', :locale=>{ employee: @employee} %> 
  </div> 
</div>

app/views/queries/new.html.erb
<h1>New Query</h1>

<%= render partial: 'form', :locale=>{ employee: @employee} %>

<%= link_to 'Back', employee_queries_path %>

app/views/queries/show.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-danger">
	<div class="panel-heading">
		<h4><strong>Query Description:</strong></h4> 
	</div>	
		<div class="panel-body">
			<h5><strong>Query Title : </strong><%= @query.title %></h5>
			<h5><strong>Query Description : </strong><%= @query.description %></h5>
		</div>
		<div class="panel-body">		
		<% @query.comments.each do |comment| %>	
			<strong><%=comment.commenter.username %></strong>: <%= comment.description %></p>
		<% end %>
	</div>
</div>		
<div class="panel panel-primary">
	<div class="panel-heading">Create Comments</div>
	<div class="panel-body">
		<%= form_for ([current_employee,@query, @query.comments.build]) do |f| %>
			<%= f.label :description %><br>
			<%= f.text_area :description%>
			</p>
			<%= f.submit %>
			</p>
		<% end %>
	</div>
<div>
	<%= button_to 'Queries',employee_queries_path(current_employee),method:'get', class: "btn btn-primary"%>
</div>