config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees 
  resources :employees do
    resources :queries do 
      resources :comments
    end
  end

     post '/employees/:id' => 'employees#employee_session' , as: :checkin_time

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/branch.rb
class Branch < ActiveRecord::Base
	belongs_to :company	
	has_many :employees	

  geocoded_by :full_address 
  after_validation :geocode 

  def full_address

  	[address_line_1, city, state,zipcode, country].compact.join(', ')
  end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :commenter, class_name: 'Employee' ,:foreign_key => 'commenter_id'
end

app/models/company.rb
class Company < ActiveRecord::Base
	mount_uploader :logo, ImageUploader
	mount_uploader :banner, ImageUploader
	
	has_many :branches
	has_many :employees
	
end

app/models/education.rb
class Education < ActiveRecord::Base

	has_and_belongs_to_many :employees

	validates :title , :presence=> true 
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         
	belongs_to :company 
	belongs_to :branch
	belongs_to :work_shift
	belongs_to :job_title
	belongs_to :job_category
	has_many :queries , :class_name => 'Query', :foreign_key => 'creater_id'
	has_many :comments, :class_name => 'Comment', :foreign_key => 'commenter_id'
	has_many :employee_sessions
	has_and_belongs_to_many :skills
	has_and_belongs_to_many :educations 

  accepts_nested_attributes_for :skills
  accepts_nested_attributes_for :educations

  def current_session
  	session = employee_sessions.last
  	if(session.blank? || (session.check_in? && session.check_out?))
  		session = employee_sessions.create!
  	else	
  		session
  	end
  end	
end

app/models/employee_session.rb
class EmployeeSession < ActiveRecord::Base
	belongs_to :employee


	def check_in
		checkin_time = Time.now
		save
	end

	def check_out
		checkout_time = Time.now
		duration = checkout_time - checkin_time 
		save
	end

	def check_in?
		!checkin_time.blank?
	end

	def check_out?
		!checkout_time.blank?
	end

end

app/models/employment_status.rb
class EmploymentStatus < ActiveRecord::Base
	validates :title , :presence=> true 
end

app/models/job_category.rb
class JobCategory < ActiveRecord::Base

has_many :employees
	
	validates :title ,:presence => true 
end

app/models/job_title.rb
class JobTitle < ActiveRecord::Base

	has_many :employees


	validates :title , :presence=> true 
	validates :description ,:presence => {:minimum =>50 ,:message=>"Please Provide Your Description in Minimum 50 Words ."} 
	validates :specification , :presence=> true 
	validates :note , :presence=> {:maixmum => 100 , :message=> "Please Provide Your Note in Maximum 100 Words ."}
end

app/models/language.rb
class Language < ActiveRecord::Base

	validates :title , :presence=> true 
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/query.rb
class Query < ActiveRecord::Base
	has_many :comments
	belongs_to :creater , class_name: 'Employee', :foreign_key => 'creater_id'
end

app/models/skill.rb
class Skill < ActiveRecord::Base

	has_and_belongs_to_many :employees

	validates :title , :presence => {:message=> "Plese Enter The Title "} 
	validates :description , :presence => true ,
	 									:length=> {:minimum => 10, :message=>"minimum 50 Words"}
end

app/models/work_shift.rb
class WorkShift < ActiveRecord::Base

	has_many :employees

	validates :start_time ,:end_time, :presence => {:message=>"Field Must Be present ?"}
	validates	:title , :presence => true
  before_save :time_diff
    
		def time_diff
	  	diff_array = [self.start_time,self.end_time].collect{|a| a.split(":").collect{|s| s.to_i}}
	  	diff_array[1][1]+=60
	  	diff_array[1][0]-=1
	  	diff_hor = diff_array[1][0] - diff_array[0][0]
	  	diff_min = diff_array[1][1] - diff_array[0][1]

	  	diff_hor += (diff_min / 60)
	  	diff_min = (diff_min % 60)
	  	self.duration  = "#{diff_hor.to_s.rjust(2,'0')}:#{diff_min.to_s.rjust(2,'0')}"
 		end	

 		def self.time_calc
  	  (0..23).to_a.collect{|a| a.to_s.rjust(2,"0")}.collect{ |a| ["00","15","30","45"].collect{ |b| "#{a}:#{b}"  }  }.flatten
    end 
	
end

app/controllers/queries_controller.rb
class QueriesController < InheritedResources::Base
 before_action :employee , only: [:index ,:new]
 before_action :query , only: [:show ]

	def index
		@queries = Query.all
	end

	def create 
		@query = Query.new(query_params)
		@query.creater = current_employee
		byebug
		if @query.save
			redirect_to employee_queries_path
		else
			render "new"
		end
	end	
 
	def show
  		
	end



  private

  def employee
  	@employee =Employee.find(params[:employee_id])
  end

  def query
  	@query = Query.find(params[:id])
  end
  
  def query_params
    params.require(:query).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def custom_bootstrap_flash
	  flash_messages = []
	  flash.each do |type, message|
	    type = 'success' if type == 'notice'
	    type = 'error'   if type == 'alert'
	    text = "<script>toastr.#{type}('#{message}');</script>"
	    flash_messages << text.html_safe if message
	  end
	  flash_messages.join("\n").html_safe
		end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Strivepool" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>



    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Strivepool</a>
      <div class="navbar-collapse collapse navbar-responsive-collapse   ">
         <div id="user_nav">
          	<ul class="pull-right" >
  						<% if employee_signed_in? %>
    						 <%= current_employee.username %>
    							<%= link_to "Sign out", destroy_employee_session_path, :method => :delete , class:"btn btn btn-default"%>
  						<% else %>
    						<%= link_to "Sign up", new_employee_registration_path %> or <%= link_to "sign in", new_employee_session_path %>
  						<% end %>
              <%= form_tag(@employee, action: 'checkin_time', method:'post') do %>
              <div> 
                <%= submit_tag 'Save' %>  
              </div> 
              <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
           <%= custom_bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>